-- Sample recipes for development. The tables themselves come from sql/createTables.sql.

INSERT INTO Recipe (id, cook, name, category) VALUES ('dev-recipe-01', 'Stanley', 'Kapustnica', 'Polievky');
INSERT INTO Recipe (id, cook, name, category) VALUES ('dev-recipe-02', 'Stanley', 'Paradajková polievka', 'Polievky');
INSERT INTO Recipe (id, cook, name, category) VALUES ('dev-recipe-03', 'Stanley', 'Bryndzové halušky', 'Hlavné jedlá');
INSERT INTO Recipe (id, cook, name, category) VALUES ('dev-recipe-04', 'Stanley', 'Kuracie na paprike', 'Hlavné jedlá');
INSERT INTO Recipe (id, cook, name, category) VALUES ('dev-recipe-05', 'Stanley', 'Cestoviny s lososom a špenátom', 'Cestoviny');
INSERT INTO Recipe (id, cook, name, category) VALUES ('dev-recipe-06', 'Stanley', 'Palacinky', 'Dezerty');
INSERT INTO Recipe (id, cook, name, category) VALUES ('dev-recipe-07', 'Stanley', 'Ovsená kaša', 'Raňajky');
INSERT INTO Recipe (id, cook, name, category) VALUES ('dev-recipe-08', 'Anna', 'Šošovicový šalát', 'Šaláty');
INSERT INTO Recipe (id, cook, name, category) VALUES ('dev-recipe-09', 'Anna', 'Bábovka', 'Dezerty');

INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-01', 'Kyslá kapusta', '500 g', false, 'dev-recipe-01');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-02', 'Klobása', '200 g', false, 'dev-recipe-01');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-03', 'Sušené huby', 'hrsť', true, 'dev-recipe-01');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-04', 'Cibuľa', '1 ks', false, 'dev-recipe-01');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-05', 'Paradajky', '800 g', false, 'dev-recipe-02');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-06', 'Cibuľa', '1 ks', false, 'dev-recipe-02');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-07', 'Bazalka', '', true, 'dev-recipe-02');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-08', 'Zemiaky', '1 kg', false, 'dev-recipe-03');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-09', 'Bryndza', '250 g', false, 'dev-recipe-03');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-10', 'Slanina', '150 g', false, 'dev-recipe-03');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-11', 'Kuracie stehná', '4 ks', false, 'dev-recipe-04');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-12', 'Cibuľa', '2 ks', false, 'dev-recipe-04');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-13', 'Sladká paprika', '2 PL', false, 'dev-recipe-04');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-14', 'Kyslá smotana', '200 ml', false, 'dev-recipe-04');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-15', 'Cestoviny', '400 g', false, 'dev-recipe-05');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-16', 'Losos', '300 g', false, 'dev-recipe-05');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-17', 'Špenát', '200 g', false, 'dev-recipe-05');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-18', 'Smotana na varenie', '200 ml', false, 'dev-recipe-05');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-19', 'Múka', '250 g', false, 'dev-recipe-06');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-20', 'Mlieko', '500 ml', false, 'dev-recipe-06');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-21', 'Vajcia', '2 ks', false, 'dev-recipe-06');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-22', 'Džem', '', true, 'dev-recipe-06');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-23', 'Ovsené vločky', '50 g', false, 'dev-recipe-07');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-24', 'Mlieko', '250 ml', false, 'dev-recipe-07');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-25', 'Šošovica', '250 g', false, 'dev-recipe-08');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-26', 'Cibuľa', '1 ks', false, 'dev-recipe-08');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-27', 'Múka', '300 g', false, 'dev-recipe-09');
INSERT INTO Ingredient (id, name, quantity, optional, recipeId) VALUES ('dev-ingr-28', 'Vajcia', '4 ks', false, 'dev-recipe-09');

INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-01', 'Na cibuli opečieme nakrájanú klobásu.', 1, false, 'dev-recipe-01');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-02', 'Pridáme kapustu, zalejeme vodou a varíme hodinu.', 2, false, 'dev-recipe-01');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-03', 'Primiešame namočené huby.', 3, true, 'dev-recipe-01');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-04', 'Cibuľu speníme, pridáme paradajky a dusíme 20 minút.', 1, false, 'dev-recipe-02');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-05', 'Rozmixujeme a dochutíme bazalkou.', 2, false, 'dev-recipe-02');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-06', 'Zemiaky nastrúhame a s múkou vypracujeme cesto.', 1, false, 'dev-recipe-03');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-07', 'Halušky hádžeme do vriacej osolenej vody.', 2, false, 'dev-recipe-03');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-08', 'Zmiešame s bryndzou a posypeme opečenou slaninou.', 3, false, 'dev-recipe-03');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-09', 'Mäso opečieme, pridáme cibuľu a papriku.', 1, false, 'dev-recipe-04');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-10', 'Podlejeme vodou a dusíme do mäkka, zjemníme smotanou.', 2, false, 'dev-recipe-04');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-11', 'Uvaríme cestoviny, losos opečieme so špenátom a zalejeme smotanou.', 1, false, 'dev-recipe-05');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-12', 'Vymiešame hladké cesto a necháme odpočinúť.', 1, false, 'dev-recipe-06');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-13', 'Pečieme na rozpálenej panvici z oboch strán.', 2, false, 'dev-recipe-06');
INSERT INTO Step (id, text, number, optional, recipeId) VALUES ('dev-step-14', 'Šošovicu uvaríme, scedíme a zmiešame s cibuľou.', 1, false, 'dev-recipe-08');
