quarkus.datasource.jdbc.url=${JDBC_URL}
quarkus.datasource.db-kind=${DB_KIND}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.http.port=${HTTP_PORT:8080}
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${FRONTEND_ORIGIN}
quarkus.http.limits.max-body-size=10M

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/api/docs
