CREATE TABLE Recipe (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name TINYTEXT NOT NULL,
image LONGBLOB,
categoryId SMALLINT UNSIGNED NOT NULL,
CONSTRAINT `fk_categoryId` FOREIGN KEY (categoryId) REFERENCES Category(id)
);