CREATE TABLE RecipeIngredient (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
quantity SMALLINT UNSIGNED NOT NULL,
unit VARCHAR(20) NOT NULL,
optional BOOLEAN,
recipeId SMALLINT UNSIGNED NOT NULL,
CONSTRAINT `fk_recipeId` FOREIGN KEY (recipeId) REFERENCES Recipe(id),
ingredientId SMALLINT UNSIGNED NOT NULL,
CONSTRAINT `fk_ingredientId` FOREIGN KEY (ingredientId) REFERENCES Ingredient(id)
);