CREATE TABLE Step (
id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
text TEXT NOT NULL,
number TINYINT NOT NULL,
optional BOOLEAN,
recipeId SMALLINT UNSIGNED NOT NULL,
CONSTRAINT `fk_StepRecipeId` FOREIGN KEY (recipeId) REFERENCES Recipe(id)
);