CREATE TABLE Category (
id VARCHAR(36) NOT NULL PRIMARY KEY,
name TINYTEXT NOT NULL
);
CREATE TABLE Recipe (
id VARCHAR(36) NOT NULL PRIMARY KEY,
name TINYTEXT NOT NULL,
image LONGBLOB,
categoryId VARCHAR(36) NOT NULL,
CONSTRAINT `fk_categoryId` FOREIGN KEY (categoryId) REFERENCES Category(id)
);
CREATE TABLE Step (
id VARCHAR(36) NOT NULL PRIMARY KEY,
text TEXT NOT NULL,
number TINYINT NOT NULL,
optional BOOLEAN,
recipeId VARCHAR(36) NOT NULL,
CONSTRAINT `fk_StepRecipeId` FOREIGN KEY (recipeId) REFERENCES Recipe(id)
);
CREATE TABLE Ingredient (
id VARCHAR(36) NOT NULL PRIMARY KEY,
name TINYTEXT NOT NULL
);
CREATE TABLE RecipeIngredient (
id VARCHAR(36) NOT NULL PRIMARY KEY,
quantity VARCHAR(20) NOT NULL,
unit VARCHAR(20) NOT NULL,
optional BOOLEAN,
recipeId VARCHAR(36) NOT NULL,
CONSTRAINT `fk_recipeId` FOREIGN KEY (recipeId) REFERENCES Recipe(id),
ingredientId VARCHAR(36) NOT NULL,
CONSTRAINT `fk_ingredientId` FOREIGN KEY (ingredientId) REFERENCES Ingredient(id)
);
